### PR TITLE
surnia: enable LTE

### PR DESCRIPTION
**Pull request by luca020400**
- Remove tty_enabled as moved to Telecomm package

### CODE REVIEW

**Comment by skritchz** [comment]
As you wrote the tty_enabled is in the Telecomm package. The file modified was indeed the Telecomm config.xml file.

I can't find the config_enabled_lte enabled key in the Telecomm package. It is available in the Telephony package though and value is already set in the overlay for the telephony package.

https://github.com/Motorola-CyanogenMod/android_device_motorola_surnia/blob/cm-12.1/overlay/packages/services/Telephony/res/values/config.xml

**Comment by luca020400** [comment]
Sorry , I read the wrong file ....
LTE should work then , I don't know why it's broken

**Comment by skritchz** [comment]
Ok then closing the pull request.

Thanks anyway for the help. I really don't know where to look anymore...

**Comment by luca020400** [comment]
What about a selinux deniel ?
Can you five me /data/misc/audit/audit.log ?

**Pull request closed without merging**
